# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running

opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # Find all the available rules by running: `swiftlint rules`

# Alternatively, specify all rules explicitly by uncommenting this option:
# only_rules: # delete `disabled_rules` & `opt_in_rules` if using this
#   - empty_parameters
#   - vertical_whitespace

# included: # paths to include during linting. `--path` is ignored if present.
#   - Source
# excluded: # paths to ignore during linting. Takes precedence over `included`.
#   - Carthage
#   - Pods
#   - Source/ExcludedFolder
#   - Source/ExcludedFile.swift
#   - Source/*/ExcludedFile.swift # Exclude files with a wildcard
# analyzer_rules: # Rules run by `swiftlint analyze`
#   - explicit_self

line_length:
  warning: 180
  error: 200
identifier_name:
  min_length: 2 # only min_length
  allowed_symbols: ["_"]
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)